### ISSUE TITLE
How to determine the number in front of the rule template in nlt files for a new dataset?

### ISSUE THREAD

**Issue by davidlvxin** [uclmr/ntp#3]
From the paper, we can know the number in front of the rule template indicates how often a parameterized rule of the given structure will be instantiated. But I still don't know how to determine this number for a new dataset like FB15K-237. Could you give me some suggestions? Thank you!

**Comment by rockt** [comment]
I think the general rule of thumb is the more the better. The number of rule templates is a hyperparameter that we usually set to maximize GPU utilization (though this is also influenced by the batch size). I would recommend starting with a small number of rule templates and large batch size, and then gradually increasing the number of rule templates and decreasing the batch size so that everything still fits on the GPU.

**Comment by davidlvxin** [comment]
OK, I know, Thank you!
